<?php

namespace AppBundle\Entity;

/**
 * ItineraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItineraryRepository extends \Doctrine\ORM\EntityRepository
{
}
