<?php

namespace AppBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
		public function findProductByLimit($limit)
    {
    	$data = $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:Product p ORDER BY p.id DESC')
            ->setMaxResults($limit)
            ->getArrayResult();

        //var_dump($data);

        return $data;
    }

    public function findProductById($id)
    {
        $data = $this->find($id);

        /* THE LONG WAY
        $parameters = array(
            'id' => $id
            );

        $dql = 'SELECT p
                FROM AppBundle:Product p
                WHERE p.id=:id';

        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters($parameters);

        $data = $query->getArrayResult();
        */
        //var_dump($result);

        return $data;
    }
}
