<?php

namespace AppBundle\Entity;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsersByEmail($email)
    {
        $parameters = array('email' => $email);

        $dql = 'SELECT u
                FROM AppBundle:Users u
                WHERE u.email=:email';

        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters($parameters);

        $data = $query->getArrayResult();

        //var_dump($data);

        return $data;
    }
}
